### ISSUE TITLE
Don´t work with Typo3 V10.4.8

### ISSUE THREAD

**Issue by heural** [b13/warmup#5]
PHP Fatal error:  Declaration of class@anonymous::isEnvironmentInFrontendMode() must be compatible with TYPO3\CMS\Extbase\Service\EnvironmentService::isEnvironmentInFrontendMode(): bool in /bigdisk/typo3/vhosts/fotoquelle/packages/warmup/Classes/FrontendRequestBuilder.php on line 55

Fixing this with:
`$environmentService = new class extends EnvironmentService {
            public function isEnvironmentInFrontendMode() : bool
            {
                return true;
            }
            public function isEnvironmentInBackendMode() : bool
            {
                return false;
            }
            public function isEnvironmentInCliMode() : bool
            {
                return false;
            }
        };`

the next error is:

Uncaught TYPO3 Exception Too few arguments to function TYPO3\CMS\Extbase\SignalSlot\Dispatcher::__construct(), 0 passed in /bigdisk/typo3/vhosts/fotoquelle/packages/warmup/Classes/FrontendRequestBuilder.php on line 70 and exactly 2 expected
thrown in file /bigdisk/typo3/vhosts/fotoquelle/web/typo3/sysext/extbase/Classes/SignalSlot/Dispatcher.php
in line 296

**Comment by sbuerk** [comment]
duplicate of #3.

The first issue with the `:bool` return types should be fixed with f992b15d4c1e578203a1148e4ba38fc85d9d99eb - or not ?

The second I cannot say, anyway with latest tag it works for us without error on 10.4.23
